CREATE TABLE TEACHER(
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  age NUMERIC(3) NOT NULL, --NUMBER(3) means INTEGER -- limit 999
  nationality VARCHAR(2) NOT NULL,
  membership VARCHAR(1) NOT NULL
);